#!/bin/sh
# ==============================================================================
# Mole — TLS config sync
#
# Runs from the stock nginx entrypoint (/docker-entrypoint.d/*) before nginx
# starts. Solves the bootstrap deadlock: nginx refuses to start when
# `ssl_certificate` points at a file that does not exist, yet nginx must
# already be serving :80 for certbot to pass the ACME HTTP-01 challenge.
#
# So the :443 server lives in a file that is only written once a certificate
# actually exists. Both nginx.conf and conf.d/default.conf include this
# directory with a GLOB, which legally matches zero files.
#
# The background poll below then covers two events with one mechanism:
#   1. first issuance — certbot writes the cert, we materialise :443 and reload
#   2. renewal        — certbot replaces the cert, we reload to pick it up
# The alternatives are worse: mounting the Docker socket into a public-facing
# certbot container is privilege escalation, and a host cron breaks the
# "one compose command" deploy. Please don't delete this loop.
# ==============================================================================

set -eu

TLS_DIR=/etc/nginx/tls.d
STATE_FILE=/var/run/mole-tls-state
POLL_SECONDS=60

domain="${MOLE_DOMAIN:-}"

log() { echo "[mole-tls-sync] $1"; }

live_cert() { echo "/etc/letsencrypt/live/$domain/fullchain.pem"; }

# Identity of the current TLS situation. The certificate mtime is part of it on
# purpose: after the first issuance the rendered config text stops changing, so
# a content-only comparison would never notice a renewal.
cert_state() {
    if [ -n "$domain" ] && [ -f "$(live_cert)" ]; then
        echo "present:${domain}:$(stat -c %Y "$(live_cert)")"
    else
        echo "absent:${domain}"
    fi
}

# NOTE: every nginx variable below is escaped (\$host, \$request_uri). An
# unescaped heredoc would let the shell expand them to empty strings and
# silently break proxying. This is also why envsubst is not used here.
render() {
    mkdir -p "$TLS_DIR"
    rm -f "$TLS_DIR"/http-root*.conf "$TLS_DIR"/ssl*.conf

    if [ -n "$domain" ] && [ -f "$(live_cert)" ]; then
        cat > "$TLS_DIR/http-root.conf" <<EOF
# Generated by 40-mole-tls-sync.sh — certificate present, so :80 only redirects.
location / {
    return 301 https://\$host\$request_uri;
}
EOF

        cat > "$TLS_DIR/ssl.conf" <<EOF
# Generated by 40-mole-tls-sync.sh — edits here are lost on container restart.
server {
    listen 443 ssl;
    http2 on;
    server_name ${domain};

    client_max_body_size 10M;

    ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    include /etc/nginx/partials/app-locations.conf;
}
EOF
        log "certificate found for ${domain} — HTTPS enabled, HTTP redirects"
    else
        cat > "$TLS_DIR/http-root.conf" <<'EOF'
# Generated by 40-mole-tls-sync.sh — no certificate yet, serving over plain HTTP.
include /etc/nginx/partials/app-locations.conf;
EOF
        if [ -z "$domain" ]; then
            log "MOLE_DOMAIN is not set — serving plain HTTP only. Set MOLE_DOMAIN and CERTBOT_EMAIL in .env to enable TLS."
        else
            log "no certificate for ${domain} yet — serving plain HTTP while certbot works"
        fi
    fi
}

render
cert_state > "$STATE_FILE"

# Backgrounded so this script exits and the stock entrypoint can exec nginx.
# The loop reparents to nginx (PID 1) and lives for the container's lifetime.
(
    while :; do
        sleep "$POLL_SECONDS"
        new_state="$(cert_state)"
        old_state="$(cat "$STATE_FILE" 2>/dev/null || echo)"
        [ "$new_state" = "$old_state" ] && continue

        log "TLS state changed (${old_state} -> ${new_state}) — re-rendering"
        render
        echo "$new_state" > "$STATE_FILE"

        if nginx -t >/dev/null 2>&1; then
            nginx -s reload
            log "nginx reloaded"
        else
            log "ERROR: generated config failed nginx -t; keeping the running config"
            nginx -t || true
        fi
    done
) &
